import ACCOUNT_SHORT_SEARCH_TERM from "@salesforce/label/c.ACCOUNT_SHORT_SEARCH_TERM";
import ACCOUNT_CREATE_MODAL_LABEL from "@salesforce/label/c.ACCOUNT_CREATE_MODAL_LABEL";
import ACCOUNT_CREATED_MESSAGE from "@salesforce/label/c.ACCOUNT_CREATED_MESSAGE";
import ACCOUNT_NEW_BUTTON_LABEL from "@salesforce/label/c.ACCOUNT_NEW_BUTTON_LABEL";
import ACCOUNT_FILTER_BY_TYPE_PLACEHOLDER from "@salesforce/label/c.ACCOUNT_FILTER_BY_TYPE_PLACEHOLDER";
import ACCOUNT_FILTER_BY_INDUSTRY_PLACEHOLDER from "@salesforce/label/c.ACCOUNT_FILTER_BY_INDUSTRY_PLACEHOLDER";
import ACCOUNT_SEARCH_BY_NAME_PLACEHOLDER from "@salesforce/label/c.ACCOUNT_SEARCH_BY_NAME_PLACEHOLDER";
import ACCOUNT_NO_AVAILABLE_ACCOUNTS from "@salesforce/label/c.ACCOUNT_NO_AVAILABLE_ACCOUNTS";

export default {
    ACCOUNT_SHORT_SEARCH_TERM,
    ACCOUNT_CREATE_MODAL_LABEL,
    ACCOUNT_CREATED_MESSAGE,
    ACCOUNT_NEW_BUTTON_LABEL,
    ACCOUNT_FILTER_BY_TYPE_PLACEHOLDER,
    ACCOUNT_FILTER_BY_INDUSTRY_PLACEHOLDER,
    ACCOUNT_SEARCH_BY_NAME_PLACEHOLDER,
    ACCOUNT_NO_AVAILABLE_ACCOUNTS
}